name: CICD
on:
  push:

jobs:
  release:
    uses: homebots/workflows/.github/workflows/node-build-release.yml@master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
